In [56]:
import pandas as pd

pd.set_option('display.max_colwidth', None)
df = pd.read_csv('dataset_tugas_regex.csv')
df.head()

                                                                                                                                  Kalimat Asli
0  Di Menteng, Jakarta, kosan sempit AC air panas 4-5juta. Di Bangkok udah bisa sewa condominium studio, udh ada fasilitas gym & kolam renang.
1                                                                                          Apakah mesin akan menggantikan pekerjaan manusia???
2                                                        Real Madrid harus memutar otak menjelang laga pekan kedelapan Liga Spanyol 2026-2027.
3                                                                                 Kylian Mbappe mengalami cedera saat membela Timnas Perancis.
4                                                                             Jangan pernah merasa lebih baik dari siapapun, dalam hal apapun.

In [64]:
import re

df['Hapus Angka'] = df['Kalimat Asli'].apply(
    lambda x: re.sub(r'\d+', '', str(x))
)

display(df[['Hapus Angka']].head(20))

                                                                                                                                                            Hapus Angka
0                             Di Menteng, Jakarta, kosan sempit AC air panas -juta. Di Bangkok udah bisa sewa condominium studio, udh ada fasilitas gym & kolam renang.
1                                                                                                                   Apakah mesin akan menggantikan pekerjaan manusia???
2                                                                                         Real Madrid harus memutar otak menjelang laga pekan kedelapan Liga Spanyol -.
3                                                                                                          Kylian Mbappe mengalami cedera saat membela Timnas Perancis.
4                                                                                                      Jangan pernah merasa lebih baik dari siapapun, dalam hal apapun.
5                                   Olivia Rodrigo berikan penampilan memukau saat menggelar konser "The Unraveled Tour" di PeoplesBank Arena, Connecticut, Jumat (//).
6   Tur "The Unraveled" dimulai dengan pertunjukan dua malam di Hartford, menandai pemberhentian pertama dari  pemberhentian tur yang mencakup Amerika Utara dan Eropa.
7                                                                                                                    Harga saham perusahaan teknologi naik .% hari ini!
8                                                                                                                  Bank Sentral menurunkan suku bunga acuan menjadi .%.
9                                                                                                     Investor asing mencatatkan pembelian bersih sebesar Rp . triliun.
10                                                                                                      Cek portofolio investasi Anda melalui www.investasi-aman.co.id.
11                                                                                                        "Inflasi bulan ini sangat terkendali," ujar Menteri Keuangan.
12                                                                                                                   Emas Antam hari ini dijual seharga Rp .. per gram.
13              Konser Sheeran yang dijadwalkan di Gillette Stadium di Foxborough, Massachusetts, pada hari Jumat,  September, dan Sabtu,  September, telah dibatalkan.
14                         Para musisi asal Papua mengobarkan semangat nasionalisme kepada para atlet Indonesia yang berlaga dalam Asian Games Aichi-Nagoya  di Jepang.
15                                                        Pada GrabX , Grab memperkenalkan  inovasi berbasis AI yang dirancang untuk memperkuat layanan yang sudah ada.
16                                                                                                             BYD Mulai Bangun Flash Charging di Jaringan Diler Denza.
17                                                                                                                  UMKM menyumbang lebih dari % terhadap PDB nasional.
18                                                                Saat ini harga BBM non-subsidi, baik untuk mesin diesel maupun bensin, sudah terbilang sangat tinggi.
19                                                              Untuk varian diesel, Dexlite kini dibanderol Rp . per liter dan Pertamina Dex menyentuh Rp . per liter.

In [ ]:
df['Hapus Tanda Baca'] = df['Hapus Angka'].apply(
    lambda x: re.sub(r'[^\w\s]', '', str(x))
)

display(df[['Hapus Tanda Baca']].tail(20))

                                                                                                                                                   Hapus Tanda Baca
0                                Di Menteng Jakarta kosan sempit AC air panas juta Di Bangkok udah bisa sewa condominium studio udh ada fasilitas gym  kolam renang
1                                                                                                                  Apakah mesin akan menggantikan pekerjaan manusia
2                                                                                       Real Madrid harus memutar otak menjelang laga pekan kedelapan Liga Spanyol
3                                                                                                       Kylian Mbappe mengalami cedera saat membela Timnas Perancis
4                                                                                                    Jangan pernah merasa lebih baik dari siapapun dalam hal apapun
5                                        Olivia Rodrigo berikan penampilan memukau saat menggelar konser The Unraveled Tour di PeoplesBank Arena Connecticut Jumat
6   Tur The Unraveled dimulai dengan pertunjukan dua malam di Hartford menandai pemberhentian pertama dari  pemberhentian tur yang mencakup Amerika Utara dan Eropa
7                                                                                                                   Harga saham perusahaan teknologi naik  hari ini
8                                                                                                                 Bank Sentral menurunkan suku bunga acuan menjadi
9                                                                                                   Investor asing mencatatkan pembelian bersih sebesar Rp  triliun
10                                                                                                       Cek portofolio investasi Anda melalui wwwinvestasiamancoid
11                                                                                                        Inflasi bulan ini sangat terkendali ujar Menteri Keuangan
12                                                                                                                  Emas Antam hari ini dijual seharga Rp  per gram
13                 Konser Sheeran yang dijadwalkan di Gillette Stadium di Foxborough Massachusetts pada hari Jumat  September dan Sabtu  September telah dibatalkan
14                       Para musisi asal Papua mengobarkan semangat nasionalisme kepada para atlet Indonesia yang berlaga dalam Asian Games AichiNagoya  di Jepang
15                                                      Pada GrabX  Grab memperkenalkan  inovasi berbasis AI yang dirancang untuk memperkuat layanan yang sudah ada
16                                                                                                          BYD Mulai Bangun Flash Charging di Jaringan Diler Denza
17                                                                                                                UMKM menyumbang lebih dari  terhadap PDB nasional
18                                                                Saat ini harga BBM nonsubsidi baik untuk mesin diesel maupun bensin sudah terbilang sangat tinggi
19                                                              Untuk varian diesel Dexlite kini dibanderol Rp  per liter dan Pertamina Dex menyentuh Rp  per liter

In [66]:
df['Hapus URL'] = df['Hapus Tanda Baca'].apply(
    lambda x: re.sub(r'http\S+|www\.\S+', '', str(x))
)

display(df[['Hapus URL']].head(20))

                                                                                                                                                          Hapus URL
0                                Di Menteng Jakarta kosan sempit AC air panas juta Di Bangkok udah bisa sewa condominium studio udh ada fasilitas gym  kolam renang
1                                                                                                                  Apakah mesin akan menggantikan pekerjaan manusia
2                                                                                       Real Madrid harus memutar otak menjelang laga pekan kedelapan Liga Spanyol
3                                                                                                       Kylian Mbappe mengalami cedera saat membela Timnas Perancis
4                                                                                                    Jangan pernah merasa lebih baik dari siapapun dalam hal apapun
5                                        Olivia Rodrigo berikan penampilan memukau saat menggelar konser The Unraveled Tour di PeoplesBank Arena Connecticut Jumat
6   Tur The Unraveled dimulai dengan pertunjukan dua malam di Hartford menandai pemberhentian pertama dari  pemberhentian tur yang mencakup Amerika Utara dan Eropa
7                                                                                                                   Harga saham perusahaan teknologi naik  hari ini
8                                                                                                                 Bank Sentral menurunkan suku bunga acuan menjadi
9                                                                                                   Investor asing mencatatkan pembelian bersih sebesar Rp  triliun
10                                                                                                       Cek portofolio investasi Anda melalui wwwinvestasiamancoid
11                                                                                                        Inflasi bulan ini sangat terkendali ujar Menteri Keuangan
12                                                                                                                  Emas Antam hari ini dijual seharga Rp  per gram
13                 Konser Sheeran yang dijadwalkan di Gillette Stadium di Foxborough Massachusetts pada hari Jumat  September dan Sabtu  September telah dibatalkan
14                       Para musisi asal Papua mengobarkan semangat nasionalisme kepada para atlet Indonesia yang berlaga dalam Asian Games AichiNagoya  di Jepang
15                                                      Pada GrabX  Grab memperkenalkan  inovasi berbasis AI yang dirancang untuk memperkuat layanan yang sudah ada
16                                                                                                          BYD Mulai Bangun Flash Charging di Jaringan Diler Denza
17                                                                                                                UMKM menyumbang lebih dari  terhadap PDB nasional
18                                                                Saat ini harga BBM nonsubsidi baik untuk mesin diesel maupun bensin sudah terbilang sangat tinggi
19                                                              Untuk varian diesel Dexlite kini dibanderol Rp  per liter dan Pertamina Dex menyentuh Rp  per liter

In [67]:
df['Teks Bersih'] = df['Hapus URL'].apply(
    lambda x: re.sub(r'\s+', ' ', str(x)).strip()
)

display(df[['Teks Bersih']].head(20))

                                                                                                                                                       Teks Bersih
0                                Di Menteng Jakarta kosan sempit AC air panas juta Di Bangkok udah bisa sewa condominium studio udh ada fasilitas gym kolam renang
1                                                                                                                 Apakah mesin akan menggantikan pekerjaan manusia
2                                                                                       Real Madrid harus memutar otak menjelang laga pekan kedelapan Liga Spanyol
3                                                                                                      Kylian Mbappe mengalami cedera saat membela Timnas Perancis
4                                                                                                   Jangan pernah merasa lebih baik dari siapapun dalam hal apapun
5                                        Olivia Rodrigo berikan penampilan memukau saat menggelar konser The Unraveled Tour di PeoplesBank Arena Connecticut Jumat
6   Tur The Unraveled dimulai dengan pertunjukan dua malam di Hartford menandai pemberhentian pertama dari pemberhentian tur yang mencakup Amerika Utara dan Eropa
7                                                                                                                   Harga saham perusahaan teknologi naik hari ini
8                                                                                                                 Bank Sentral menurunkan suku bunga acuan menjadi
9                                                                                                   Investor asing mencatatkan pembelian bersih sebesar Rp triliun
10                                                                                                      Cek portofolio investasi Anda melalui wwwinvestasiamancoid
11                                                                                                       Inflasi bulan ini sangat terkendali ujar Menteri Keuangan
12                                                                                                                  Emas Antam hari ini dijual seharga Rp per gram
13                  Konser Sheeran yang dijadwalkan di Gillette Stadium di Foxborough Massachusetts pada hari Jumat September dan Sabtu September telah dibatalkan
14                       Para musisi asal Papua mengobarkan semangat nasionalisme kepada para atlet Indonesia yang berlaga dalam Asian Games AichiNagoya di Jepang
15                                                       Pada GrabX Grab memperkenalkan inovasi berbasis AI yang dirancang untuk memperkuat layanan yang sudah ada
16                                                                                                         BYD Mulai Bangun Flash Charging di Jaringan Diler Denza
17                                                                                                                UMKM menyumbang lebih dari terhadap PDB nasional
18                                                               Saat ini harga BBM nonsubsidi baik untuk mesin diesel maupun bensin sudah terbilang sangat tinggi
19                                                               Untuk varian diesel Dexlite kini dibanderol Rp per liter dan Pertamina Dex menyentuh Rp per liter

In [68]:
df['Kata Kapital'] = df['Kalimat Asli'].apply(
    lambda x: re.findall(r'\b[A-Z][a-zA-Z]*\b', str(x))
)

display(df[['Kata Kapital']].head(20))

                                                                                           Kata Kapital
0                                                               [Di, Menteng, Jakarta, AC, Di, Bangkok]
1                                                                                              [Apakah]
2                                                                         [Real, Madrid, Liga, Spanyol]
3                                                                    [Kylian, Mbappe, Timnas, Perancis]
4                                                                                              [Jangan]
5                       [Olivia, Rodrigo, The, Unraveled, Tour, PeoplesBank, Arena, Connecticut, Jumat]
6                                                [Tur, The, Unraveled, Hartford, Amerika, Utara, Eropa]
7                                                                                               [Harga]
8                                                                                       [Bank, Sentral]
9                                                                                        [Investor, Rp]
10                                                                                          [Cek, Anda]
11                                                                         [Inflasi, Menteri, Keuangan]
12                                                                                    [Emas, Antam, Rp]
13  [Konser, Sheeran, Gillette, Stadium, Foxborough, Massachusetts, Jumat, September, Sabtu, September]
14                                        [Para, Papua, Indonesia, Asian, Games, Aichi, Nagoya, Jepang]
15                                                                              [Pada, GrabX, Grab, AI]
16                                        [BYD, Mulai, Bangun, Flash, Charging, Jaringan, Diler, Denza]
17                                                                                          [UMKM, PDB]
18                                                                                          [Saat, BBM]
19                                                             [Untuk, Dexlite, Rp, Pertamina, Dex, Rp]

In [69]:
df['Kata Lebih 5 Huruf'] = df['Kalimat Asli'].apply(
    lambda x: re.findall(r'\b\w{6,}\b', str(x))
)

display(df[['Kata Lebih 5 Huruf']].head(20))

                                                                                                         Kata Lebih 5 Huruf
0                                               [Menteng, Jakarta, sempit, Bangkok, condominium, studio, fasilitas, renang]
1                                                                                [Apakah, menggantikan, pekerjaan, manusia]
2                                                                          [Madrid, memutar, menjelang, kedelapan, Spanyol]
3                                                            [Kylian, Mbappe, mengalami, cedera, membela, Timnas, Perancis]
4                                                                                [Jangan, pernah, merasa, siapapun, apapun]
5                   [Olivia, Rodrigo, berikan, penampilan, memukau, menggelar, konser, Unraveled, PeoplesBank, Connecticut]
6   [Unraveled, dimulai, dengan, pertunjukan, Hartford, menandai, pemberhentian, pertama, pemberhentian, mencakup, Amerika]
7                                                                                                   [perusahaan, teknologi]
8                                                                                            [Sentral, menurunkan, menjadi]
9                                                              [Investor, mencatatkan, pembelian, bersih, sebesar, triliun]
10                                                                              [portofolio, investasi, melalui, investasi]
11                                                                         [Inflasi, sangat, terkendali, Menteri, Keuangan]
12                                                                                                        [dijual, seharga]
13           [Konser, Sheeran, dijadwalkan, Gillette, Stadium, Foxborough, Massachusetts, September, September, dibatalkan]
14                                [musisi, mengobarkan, semangat, nasionalisme, kepada, Indonesia, berlaga, Nagoya, Jepang]
15                                                      [memperkenalkan, inovasi, berbasis, dirancang, memperkuat, layanan]
16                                                                                             [Bangun, Charging, Jaringan]
17                                                                                         [menyumbang, terhadap, nasional]
18                                                             [subsidi, diesel, maupun, bensin, terbilang, sangat, tinggi]
19                                                              [varian, diesel, Dexlite, dibanderol, Pertamina, menyentuh]