In [1]:
import pandas as pd
import nltk
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
df = pd.read_excel('dataset_tugas_week4_stk.xlsx')
df

    No                                           Komentar
0    1      developer Capcut sama Spotify penghuni neraka
1    2  gara-gara bilang mbg disetop, pak purbaya diga...
2    3  fiks klw ada Mentri mendadak di copot udah pas...
3    4  Dari awal ngejabat berita baiknya bisa diitung...
4    5                 prabowo sedang menasehati subianto
5    6                       prabowo yg harus nya d copot
6    7                         cara mecat presiden gimna?
7    8  orang yang ngabisin anggaran buat program ga j...
8    9  pejabat mikir nya perut sendiri ketimbang kese...
9   10  efek gapunya someone to talk jd kl pidato isin...
10  11                    gua stress ngeliat presiden ini
11  12                     gak penting mulu isi pidatonya
12  13  bahkan dia blm sempet beresin barang dia di ru...
13  14   mereka sudah senang pemimpin yg jujur udah cabut
14  15  Kayaknya beliau emang tipe orang yang belum bi...
15  16                  DIPAKSA SEHAT DINEGARA YANG SAKIT
16  17  katanya nda mau ke militer militeran, baru na ...
17  18  disini kita belajar, yg sudah tertakar tidak a...
18  19                      tulus banget abangnya bantuin
19  20              giliran hal normal kita malah bingung

In [3]:
def casefolding(text):
    return text.lower()

df['Hasil Casefolding'] = df['Komentar'].apply(casefolding)
hasil = pd.DataFrame(df['Hasil Casefolding'])

hasil

                                    Hasil Casefolding
0       developer capcut sama spotify penghuni neraka
1   gara-gara bilang mbg disetop, pak purbaya diga...
2   fiks klw ada mentri mendadak di copot udah pas...
3   dari awal ngejabat berita baiknya bisa diitung...
4                  prabowo sedang menasehati subianto
5                        prabowo yg harus nya d copot
6                          cara mecat presiden gimna?
7   orang yang ngabisin anggaran buat program ga j...
8   pejabat mikir nya perut sendiri ketimbang kese...
9   efek gapunya someone to talk jd kl pidato isin...
10                    gua stress ngeliat presiden ini
11                     gak penting mulu isi pidatonya
12  bahkan dia blm sempet beresin barang dia di ru...
13   mereka sudah senang pemimpin yg jujur udah cabut
14  kayaknya beliau emang tipe orang yang belum bi...
15                  dipaksa sehat dinegara yang sakit
16  katanya nda mau ke militer militeran, baru na ...
17  disini kita belajar, yg sudah tertakar tidak a...
18                      tulus banget abangnya bantuin
19              giliran hal normal kita malah bingung

In [4]:
stopwords = set(stopwords.words('indonesian'))

tambahan_stopword = ['yg', 'd', 'di', 'ke', 'dari', 'klw', 'ga', 'jd', 'kl', 'gk', 'tpi', 'smw', 'udh']
stopwords.update(tambahan_stopword)

def clean_stopwords(text):
    text = ' '.join(word for word in text.split() if word not in stopwords)
    return text

df['Hasil Stopword'] = df['Hasil Casefolding'].apply(clean_stopwords)

stopwordremoval = pd.DataFrame(df['Hasil Stopword'])
stopwordremoval

                                       Hasil Stopword
0            developer capcut spotify penghuni neraka
1      gara-gara bilang mbg disetop, purbaya diganti.
2   fiks mentri mendadak copot udah mentri ajak ko...
3                ngejabat berita baiknya diitung jari
4                         prabowo menasehati subianto
5                                   prabowo nya copot
6                               mecat presiden gimna?
7           orang ngabisin anggaran program dihormati
8   pejabat mikir nya perut ketimbang kesejahteraa...
9   efek gapunya someone to talk pidato isinya cer...
10                        gua stress ngeliat presiden
11                             gak mulu isi pidatonya
12  blm sempet beresin barang ruanganya, rekan ker...
13                   senang pemimpin jujur udah cabut
14  kayaknya beliau emang tipe orang mengevaluasi ...
15                       dipaksa sehat dinegara sakit
16  nda militer militeran, na terapkan ospek gaya ...
17                         belajar, tertakar tertukar
18                      tulus banget abangnya bantuin
19                             giliran normal bingung

In [5]:
def get_stemmed_term(text):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    hasil = stemmer.stem(text)
    return hasil

df['Hasil Stemming'] = df['Hasil Stopword'].apply(get_stemmed_term)
stemmingSastrawi = pd.DataFrame(df['Hasil Stemming'])

stemmingSastrawi

                                       Hasil Stemming
0                developer capcut spotify huni neraka
1            gara-gara bilang mbg setop purbaya ganti
2            fiks tri dadak copot udah tri ajak korup
3                   ngejabat berita baik diitung jari
4                            prabowo nasehat subianto
5                                   prabowo nya copot
6                                mecat presiden gimna
7                orang ngabisin anggar program hormat
8    jabat mikir nya perut ketimbang sejahtera rakyat
9   efek gapunya someone to talk pidato isi cerita...
10                        gua stress ngeliat presiden
11                                gak mulu isi pidato
12  blm sempet resin barang ruanganya rekan kerja ...
13                     senang pimpin jujur udah cabut
14        kayak beliau emang tipe orang evaluasi diri
15                           paksa sehat negara sakit
16    nda militer militer na terap ospek gaya militer
17                                   ajar takar tukar
18                         tulus banget abang bantuin
19                               gilir normal bingung

In [6]:
def word_tokens(text):
    token = word_tokenize(text)
    return token

df['Hasil Tokenisasi'] = df['Hasil Stemming'].apply(word_tokens)
tokenkata = pd.DataFrame(df['Hasil Tokenisasi'])

tokenkata

                                     Hasil Tokenisasi
0          [developer, capcut, spotify, huni, neraka]
1     [gara-gara, bilang, mbg, setop, purbaya, ganti]
2   [fiks, tri, dadak, copot, udah, tri, ajak, korup]
3             [ngejabat, berita, baik, diitung, jari]
4                        [prabowo, nasehat, subianto]
5                               [prabowo, nya, copot]
6                            [mecat, presiden, gimna]
7          [orang, ngabisin, anggar, program, hormat]
8   [jabat, mikir, nya, perut, ketimbang, sejahter...
9   [efek, gapunya, someone, to, talk, pidato, isi...
10                   [gua, stress, ngeliat, presiden]
11                           [gak, mulu, isi, pidato]
12  [blm, sempet, resin, barang, ruanganya, rekan,...
13               [senang, pimpin, jujur, udah, cabut]
14  [kayak, beliau, emang, tipe, orang, evaluasi, ...
15                      [paksa, sehat, negara, sakit]
16  [nda, militer, militer, na, terap, ospek, gaya...
17                               [ajar, takar, tukar]
18                    [tulus, banget, abang, bantuin]
19                           [gilir, normal, bingung]

In [7]:
komen_asli = pd.Series(df['Komentar'])
casefolding = pd.Series(df['Hasil Casefolding'])
stopwordremoval = pd.Series(df['Hasil Stopword'])
stemming = pd.Series(df['Hasil Stemming'])
tokenisasi = pd.Series(df['Hasil Tokenisasi'])

df = pd.DataFrame({
    'Komentar Asli': komen_asli,
    'Hasil Casefolding': casefolding,
    'Hasil Stopword Removal': stopwordremoval,
    'Hasil Stem': stemming,
    'Hasil Tokenisasi': tokenisasi
})

df.to_excel('Hasil Prapemrosesan.xlsx', index=False)

In [8]:
df_skenario = pd.DataFrame()
df_skenario['Komentar Asli'] = df['Komentar Asli']

df_skenario['Skenario_Casefolding'] = df_skenario['Komentar Asli'].str.lower()

df_skenario['Skenario_Stemming'] = df_skenario['Skenario_Casefolding'].apply(get_stemmed_term)

df_skenario['Skenario_Stopword'] = df_skenario['Skenario_Stemming'].apply(clean_stopwords)

df_skenario['Skenario_Tokenisasi'] = df_skenario['Skenario_Stopword'].apply(word_tokens)

df_perbandingan = pd.DataFrame({
    'Komentar Asli': df['Komentar Asli'],
    'Tokenisasi (Stopword lalu Stemming)': df['Hasil Tokenisasi'],
    'Tokenisasi (Stemming lalu Stopword)': df_skenario['Skenario_Tokenisasi']
})

df_perbandingan

,Komentar Asli,Tokenisasi (Stopword lalu Stemming),Tokenisasi (Stemming lalu Stopword)
0,developer Capcut sama Spotify penghuni neraka,"[developer, capcut, spotify, huni, neraka]","[developer, capcut, spotify, huni, neraka]"
1,"gara-gara bilang mbg disetop, pak purbaya diga...","[gara-gara, bilang, mbg, setop, purbaya, ganti]","[gara-gara, bilang, mbg, setop, purbaya, ganti]"
2,fiks klw ada Mentri mendadak di copot udah pas...,"[fiks, tri, dadak, copot, udah, tri, ajak, korup]","[fiks, tri, dadak, copot, udah, tri, ajak, korup]"
3,Dari awal ngejabat berita baiknya bisa diitung...,"[ngejabat, berita, baik, diitung, jari]","[ngejabat, berita, diitung, jari]"
4,prabowo sedang menasehati subianto,"[prabowo, nasehat, subianto]","[prabowo, nasehat, subianto]"
5,prabowo yg harus nya d copot,"[prabowo, nya, copot]","[prabowo, nya, copot]"
6,cara mecat presiden gimna?,"[mecat, presiden, gimna]","[mecat, presiden, gimna]"
7,orang yang ngabisin anggaran buat program ga j...,"[orang, ngabisin, anggar, program, hormat]","[orang, ngabisin, anggar, program, hormat]"
8,pejabat mikir nya perut sendiri ketimbang kese...,"[jabat, mikir, nya, perut, ketimbang, sejahter...","[jabat, mikir, nya, perut, ketimbang, sejahter..."
9,efek gapunya someone to talk jd kl pidato isin...,"[efek, gapunya, someone, to, talk, pidato, isi...","[efek, gapunya, someone, to, talk, pidato, isi..."
10,gua stress ngeliat presiden ini,"[gua, stress, ngeliat, presiden]","[gua, stress, ngeliat, presiden]"
11,gak penting mulu isi pidatonya,"[gak, mulu, isi, pidato]","[gak, mulu, isi, pidato]"
12,bahkan dia blm sempet beresin barang dia di ru...,"[blm, sempet, resin, barang, ruanganya, rekan,...","[blm, sempet, resin, barang, ruanganya, rekan,..."
13,mereka sudah senang pemimpin yg jujur udah cabut,"[senang, pimpin, jujur, udah, cabut]","[senang, pimpin, jujur, udah, cabut]"
14,Kayaknya beliau emang tipe orang yang belum bi...,"[kayak, beliau, emang, tipe, orang, evaluasi, ...","[kayak, beliau, emang, tipe, orang, evaluasi]"
15,DIPAKSA SEHAT DINEGARA YANG SAKIT,"[paksa, sehat, negara, sakit]","[paksa, sehat, negara, sakit]"
16,"katanya nda mau ke militer militeran, baru na ...","[nda, militer, militer, na, terap, ospek, gaya...","[nda, militer, militer, na, terap, ospek, gaya..."
17,"disini kita belajar, yg sudah tertakar tidak a...","[ajar, takar, tukar]","[ajar, takar, tukar]"
18,tulus banget abangnya bantuin,"[tulus, banget, abang, bantuin]","[tulus, banget, abang, bantuin]"
19,giliran hal normal kita malah bingung,"[gilir, normal, bingung]","[gilir, normal, bingung]"